export const FETCH_DATA = "FETCH_DATA";
export const INPUT_VALUE_UPDATE = "INPUT_VALUE_UPDATE";
export const CURRENT_NATION_VIEW_UPDATE = "CURRENT_NATION_VIEW_UPDATE";
export const DISPLAY_MODE_UPDATE = "DISPLAY_MODE_UPDATE";
export const SELECT_VALUE_UPDATE = "SELECT_VALUE_UPDATE";
